"""troubleshooting a problem in migration

Revision ID: 087560ef26a7
Revises: 9ef3313d1fc0
Create Date: 2026-06-15 18:51:44.400684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '087560ef26a7'
down_revision: Union[str, Sequence[str], None] = '9ef3313d1fc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
